default_context:
  _pegasus_version: 0.13.2
  author_name: Gyana Developers
  css_framework: tailwind
  database: postgres
  deploy_platform: heroku
  description: No-code data science
  domain_name: gyana.com
  email: developers@gyana.com
  enable_google_login: y
  project_name: Gyana
  project_slug: gyana
  use_docker: n
  use_subscriptions: y
  use_teams: y
