[tool.poetry]
name = "gyana"
version = "0.1.0"
description = "No-Code Data Analytics"
authors = ["Gyana Developers <developers@gyana.com>"]

[tool.poetry.dependencies]
python = "3.8.*"
attrs = "^20.3.0"
Django = "^3.1.7"
django-allauth = "^0.44.0"
psycopg2-binary = "^2.8.6"
djangorestframework = "^3.12.2"
coreapi = "^2.3.3"
django-anymail = {extras = ["mailgun"], version = "^8.2"}
celery-progress = "^0.1.0"
celery = {extras = ["redis"], version = "^5.0.5"}
gunicorn = "^20.0.4"
django-heroku = "^0.3.1"
stripe = "^2.56.0"
dj-stripe = "^2.4.3"
google-cloud-bigquery = "^2.14.0"
django-crispy-forms = "^1.11.2"
crispy-tailwind = "^0.5.0"
django-turbo-response = "^0.0.48"
django-turbo-allauth = "^0.0.9"
pandas = "^1.2.4"
pyarrow = "^4.0.0"
ibis-bigquery = "^0.1.1"
django-storages = {extras = ["google"], version = "^1.11.1"}
django-filter = "^2.4.0"
backoff = "^1.10.0"
PyYAML = "^5.4.1"
inflection = "^0.5.1"
django-tables2 = "^2.3.4"
google-api-python-client = "^2.4.0"
analytics-python = "^1.3.1"
django-clone = "^2.5.3"
lark = "^0.11.3"
django-dirtyfields = "^1.7.0"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
isort = "^5.7.0"
mypy = "^0.812"
autoflake = "^1.4"
ipython = "^7.21.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
