adroll:
  service_type: reporting_api
  static_config:
    table: adroll_table
amplitude: {}
apple_search_ads: {}
asana: {}
aurora:
  service_type: database
aurora_postgres:
  service_type: database
azure_postgres:
  service_type: database
azure_sql_db:
  service_type: database
bingads: {}
braintree: {}
branch: {}
delighted: {}
dynamodb: {}
facebook_ad_account:
  sunset: true
facebook_ads:
  default_tables:
    - campaign
  static_config:
    timeframe_months: TWELVE
    custom_tables:
      - table_name: campaign
        config_type: Custom
        aggregation: Day
        level: campaign
        action_breakdowns:
          - action_type
        fields:
          - spend
          - campaign_id
          - campaign_name
          - actions
          - action_values
          - account_id
          - impressions
          - clicks
          - inline_link_clicks
          - frequency
facebook_pages: {}
freshdesk: {}
front: {}
github: {}
adwords:
  hide: true
  static_config:
    sync_mode: AllAccounts
    timeframe_months: TWELVE
google_ads:
  default_tables:
    - campaign
  static_config:
    sync_mode: AllAccounts
    timeframe_months: TWELVE
    reports:
      - table: campaign
        config_type: Custom
        report_type: campaign
        fields:
          - segments.date
          - segments.device
          - segments.ad_network_type
          - campaign.name
          - campaign.id
          - metrics.conversions
          - metrics.conversions_value
          - metrics.clicks
          - metrics.cost_micros
      - table: adgroup
        config_type: Custom
        report_type: ad_group
        fields:
          - segments.date
          - segments.device
          - segments.ad_network_type
          - ad_group.id
          - ad_group.name
          - campaign.name
          - campaign.id
          - metrics.conversions
          - metrics.conversions_value
          - metrics.clicks
          - metrics.cost_micros
google_analytics:
  static_config:
    sync_mode: AllAccounts
    timeframe_months: TWELVE
    default_tables:
      - campaign_stats
    reports:
      - table: campaign_stats
        config_type: Custom
        dimensions:
          - date
          - country
          - deviceCategory
          - campaign
          - userType
          - region
        metrics:
          - transactions
          - transactionRevenue
          - users
          - impressions
      - table: adwords_campaigns
        config_type: Prebuilt
        prebuilt_report: ADWORDS_CAMPAIGNS
      - table: adwords_hourly_stats
        config_type: Prebuilt
        prebuilt_report: ADWORDS_HOURLY_STATS
      - table: adwords_keyword
        config_type: Prebuilt
        prebuilt_report: ADWORDS_KEYWORD
      - table: audience_overview
        config_type: Prebuilt
        prebuilt_report: AUDIENCE_OVERVIEW
      - table: browser_and_operating_system_overview
        config_type: Prebuilt
        prebuilt_report: BROWSER_AND_OPERATING_SYSTEM_OVERVIEW
      - table: campaign_performance
        config_type: Prebuilt
        prebuilt_report: CAMPAIGN_PERFORMANCE
      - table: channel_traffic
        config_type: Prebuilt
        prebuilt_report: CHANNEL_TRAFFIC
      - table: events_overview
        config_type: Prebuilt
        prebuilt_report: EVENTS_OVERVIEW
      - table: social_media_acquisitions
        config_type: Prebuilt
        prebuilt_report: SOCIAL_MEDIA_ACQUISITIONS
      - table: traffic
        config_type: Prebuilt
        prebuilt_report: TRAFFIC
google_analytics_4: {}
google_cloud_postgresql:
  service_type: database
google_cloud_mysql:
  service_type: database
google_search_console: {}
google_sheets:
  internal: true
  service_type: reporting_api
  static_config:
    table: sheets_table
greenhouse: {}
heap: {}
height: {}
helpscout: {}
heroku_postgres:
  service_type: database
hubspot: {}
instagram_business: {}
intercom: {}
jira: {}
linkedin_company_pages: {}
klaviyo: {}
kustomer: {}
lever: {}
linkedin_ads: {}
loaded_commerce_via_mysql:
  id: loaded_commerce_via_mysql
  alias: mysql
  name: Loaded Commerce
  icon_path: loaded_commerce_via_mysql.png
  type: Commerce
magento_mysql:
  service_type: database
  type: Commerce
magento_mysql_rds:
  service_type: database
  type: Commerce
mailchimp: {}
mandrill: {}
maria:
  service_type: database
maria_rds:
  service_type: database
maria_azure:
  service_type: database
mixpanel: {}
mongo:
  service_type: database
mysql:
  service_type: database
mysql_azure:
  service_type: database
mysql_rds:
  service_type: database
oscommerce_mysql:
  id: oscommerce_mysql
  alias: mysql
  name: OsCommerce
  icon_path: oscommerce_mysql.svg
  type: Commerce
outbrain: {}
pardot: {}
pinterest_ads: {}
pipedrive: {}
postgres:
  service_type: database
postgres_rds:
  service_type: database
prestashop_via_mysql:
  id: prestashop_via_mysql
  alias: mysql
  name: PrestaShop
  icon_path: prestashop_via_mysql.svg
  type: Commerce
quickbooks: {}
recharge: {}
recurly: {}
sage_intacct: {}
salesforce: {}
segment:
  service_type: event_tracking
sendgrid: {}
shopify:
  type: Commerce
snapchat_ads: {}
snowplow:
  service_type: event_tracking
spree_commerce_via_mysql:
  id: spree_commerce_via_mysql
  alias: mysql
  name: Spree Commerce
  icon_path: spree_commerce_via_mysql.png
  type: Commerce
sql_server:
  service_type: database
sql_server_rds:
  service_type: database
square: {}
stripe: {}
survey_monkey: {}
taboola: {}
tiktok_ads: {}
twilio: {}
twitter: {}
typeform: {}
webhooks:
  service_type: webhooks
  static_config:
    table: webhooks_table
woocommerce_via_mysql:
  id: woocommerce_via_mysql
  alias: mysql
  name: WooCommerce
  icon_path: woocommerce_via_mysql.svg
  type: Commerce
uservoice: {}
xero: {}
youtube_analytics:
  service_type: reporting_api
  static_config:
    table: youtube_analytics_table
zendesk: {}
zendesk_chat: {}
zendesk_sunshine: {}
